---
apiVersion: v1
kind: Service
metadata:
  name: beers
  labels: { app.kubernetes.io/name: beers }
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector: { app.kubernetes.io/name: beers }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beers
  labels: { app.kubernetes.io/name: beers }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: beers }
  template:
    metadata:
      labels: { app.kubernetes.io/name: beers }
    spec:
      containers:
        - name: beers
          image: beers:0.1.0
          imagePullPolicy: Never
          env:
            - { name: PORT, value: "8000" }
          ports:
            - name: grpc
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:8000"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:8000"]
            initialDelaySeconds: 5

---
