// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/beers/beers.proto

package beers

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK  Status = 0
	Status_BAD Status = 1
)

var Status_name = map[int32]string{
	0: "OK",
	1: "BAD",
}

var Status_value = map[string]int32{
	"OK":  0,
	"BAD": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0569ad8cb3041009, []int{0}
}

type BeerAddResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=beers.Status" json:"status,omitempty"`
	ErrMsg               string   `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerAddResponse) Reset()         { *m = BeerAddResponse{} }
func (m *BeerAddResponse) String() string { return proto.CompactTextString(m) }
func (*BeerAddResponse) ProtoMessage()    {}
func (*BeerAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0569ad8cb3041009, []int{0}
}

func (m *BeerAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerAddResponse.Unmarshal(m, b)
}
func (m *BeerAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerAddResponse.Marshal(b, m, deterministic)
}
func (m *BeerAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerAddResponse.Merge(m, src)
}
func (m *BeerAddResponse) XXX_Size() int {
	return xxx_messageInfo_BeerAddResponse.Size(m)
}
func (m *BeerAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeerAddResponse proto.InternalMessageInfo

func (m *BeerAddResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BeerAddResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BeerAddResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *BeerAddResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type BeerAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerAddRequest) Reset()         { *m = BeerAddRequest{} }
func (m *BeerAddRequest) String() string { return proto.CompactTextString(m) }
func (*BeerAddRequest) ProtoMessage()    {}
func (*BeerAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0569ad8cb3041009, []int{1}
}

func (m *BeerAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerAddRequest.Unmarshal(m, b)
}
func (m *BeerAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerAddRequest.Marshal(b, m, deterministic)
}
func (m *BeerAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerAddRequest.Merge(m, src)
}
func (m *BeerAddRequest) XXX_Size() int {
	return xxx_messageInfo_BeerAddRequest.Size(m)
}
func (m *BeerAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeerAddRequest proto.InternalMessageInfo

func (m *BeerAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("beers.Status", Status_name, Status_value)
	proto.RegisterType((*BeerAddResponse)(nil), "beers.BeerAddResponse")
	proto.RegisterType((*BeerAddRequest)(nil), "beers.BeerAddRequest")
}

func init() { proto.RegisterFile("pkg/grpc/proto/beers/beers.proto", fileDescriptor_0569ad8cb3041009) }

var fileDescriptor_0569ad8cb3041009 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x51, 0x4b, 0xc3, 0x40,
	0x0c, 0xc7, 0x77, 0xed, 0x7a, 0xc3, 0x80, 0x75, 0x04, 0xd4, 0xea, 0x53, 0x29, 0x0a, 0xc5, 0x87,
	0x15, 0x26, 0xf8, 0x2a, 0x1d, 0xbe, 0x89, 0x08, 0xe7, 0x07, 0x90, 0xcd, 0x0b, 0xc7, 0x90, 0xad,
	0x67, 0x72, 0xfd, 0xfe, 0xe2, 0xdd, 0x98, 0xe8, 0x4b, 0x48, 0xfe, 0x21, 0xbf, 0x7f, 0x12, 0xa8,
	0xfd, 0xa7, 0xeb, 0x1c, 0xfb, 0x8f, 0xce, 0xf3, 0x10, 0x86, 0x6e, 0x43, 0xc4, 0x92, 0xe2, 0x22,
	0x2a, 0x58, 0xc4, 0xa2, 0x19, 0xe1, 0x6c, 0x45, 0xc4, 0xbd, 0xb5, 0x86, 0xc4, 0x0f, 0x7b, 0x21,
	0x2c, 0x21, 0xdb, 0xda, 0x4a, 0xd5, 0xaa, 0x2d, 0x4c, 0xb6, 0xb5, 0x88, 0x30, 0xdd, 0xaf, 0x77,
	0x54, 0x65, 0xb5, 0x6a, 0x4f, 0x4c, 0xcc, 0xf1, 0x16, 0xb4, 0x84, 0x75, 0x18, 0xa5, 0xca, 0x6b,
	0xd5, 0x96, 0xcb, 0xd3, 0x45, 0x62, 0xbf, 0x45, 0xd1, 0x1c, 0x9a, 0x78, 0x09, 0x33, 0x62, 0x7e,
	0xdf, 0x89, 0xab, 0xa6, 0x71, 0x5a, 0x13, 0xf3, 0x8b, 0xb8, 0xe6, 0x06, 0xca, 0xa3, 0xed, 0xd7,
	0x48, 0x12, 0x8e, 0x2e, 0xea, 0xd7, 0xe5, 0xee, 0x0a, 0x74, 0x02, 0xa2, 0x86, 0xec, 0xf5, 0x79,
	0x3e, 0xc1, 0x19, 0xe4, 0xab, 0xfe, 0x69, 0xae, 0x96, 0x8f, 0x50, 0xfc, 0x00, 0x04, 0x1f, 0x20,
	0xef, 0xad, 0xc5, 0xf3, 0xc3, 0x02, 0x7f, 0xa9, 0xd7, 0x17, 0xff, 0xe5, 0x74, 0x63, 0x33, 0xd9,
	0xe8, 0xf8, 0x86, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x43, 0x6d, 0x07, 0x2a, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeersClient is the client API for Beers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeersClient interface {
	Add(ctx context.Context, in *BeerAddRequest, opts ...grpc.CallOption) (*BeerAddResponse, error)
}

type beersClient struct {
	cc *grpc.ClientConn
}

func NewBeersClient(cc *grpc.ClientConn) BeersClient {
	return &beersClient{cc}
}

func (c *beersClient) Add(ctx context.Context, in *BeerAddRequest, opts ...grpc.CallOption) (*BeerAddResponse, error) {
	out := new(BeerAddResponse)
	err := c.cc.Invoke(ctx, "/beers.Beers/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeersServer is the server API for Beers service.
type BeersServer interface {
	Add(context.Context, *BeerAddRequest) (*BeerAddResponse, error)
}

// UnimplementedBeersServer can be embedded to have forward compatible implementations.
type UnimplementedBeersServer struct {
}

func (*UnimplementedBeersServer) Add(ctx context.Context, req *BeerAddRequest) (*BeerAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterBeersServer(s *grpc.Server, srv BeersServer) {
	s.RegisterService(&_Beers_serviceDesc, srv)
}

func _Beers_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeerAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeersServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beers.Beers/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeersServer).Add(ctx, req.(*BeerAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Beers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beers.Beers",
	HandlerType: (*BeersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Beers_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/beers/beers.proto",
}
