name: Release
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Default
    runs-on: ubuntu-latest
    steps:

    - name: Install Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout repository
      uses: actions/checkout@v1
    - run: |
        git branch --create-reflog master origin/master
        git fetch --tags
        go build

    - name: Release
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}