name: Review
on: [pull_request]
jobs:

  build:
    name: Default
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Go 1.13
        uses: actions/setup-go@v1

      - name: Build
        run: |
          go build

      - name: Run tests
        run: go test -v ./... -race